version: '2.2'
services:

  fluentd-test:
    image: 'fluent/fluentd:latest'
    mem_limit: 128m
    cpus: '0.2'
    volumes:
      - './test:/fluentd/etc/test'
    environment:
      FLUENTD_CONF: 'test/fluentd.conf'
    expose:
      - '24224'


  docker-monitor:
    build: .
    mem_limit: 48m
    cpus: '0.2'
    environment:
      SID: 'my special identifier'
      DEBUG: 'false'
      FLUENTD_HOST: 'fluentd-test'
      FLUENTD_PORT: '24224'
      TAG_PREFIX: 'testing_docker_monitor'
      WAIT_TIME: '120'
      DOCKER_SOCKET: 'unix:///tmp/docker.sock'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'

